# Generated by Django 5.1.4 on 2025-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='harmful_materials',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.harmfulmaterial'),
        ),
        migrations.AddField(
            model_name='post',
            name='harmful_tools',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.harmfultool'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
