# Generated by Django 5.1.4 on 2025-01-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_material_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='post',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
