# Generated by Django 5.1.4 on 2025-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_material_post_alter_tool_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='default_image_index',
            field=models.IntegerField(default=1),
        ),
    ]
