# Generated by Django 5.1.4 on 2025-01-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_default_image_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmfulMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarmfulToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='harmful_materials',
        ),
        migrations.RemoveField(
            model_name='post',
            name='harmful_tools',
        ),
        migrations.AddField(
            model_name='post',
            name='harmful_material_categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.harmfulmaterialcategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='harmful_tool_categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.harmfultoolcategory'),
        ),
        migrations.DeleteModel(
            name='HarmfulMaterial',
        ),
        migrations.DeleteModel(
            name='HarmfulTool',
        ),
    ]
