# Generated by Django 5.1.4 on 2025-01-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_harmfulmaterialcategory_harmfultoolcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='harmful_post',
            field=models.BooleanField(default=False),
        ),
    ]
