# Generated by Django 5.1.4 on 2025-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_harmful_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='default_image_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
