# Generated by Django 5.1.4 on 2025-01-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_default_image_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='default_image_index',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='harmful_material_categories',
            field=models.ManyToManyField(related_name='posts', to='posts.harmfulmaterialcategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='harmful_tool_categories',
            field=models.ManyToManyField(related_name='posts', to='posts.harmfultoolcategory'),
        ),
    ]
