# Generated by Django 5.1.4 on 2025-02-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_ratings_alter_rating_post_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ratings',
        ),
    ]
